# -*- coding: utf-8 -*-
"""Alignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBTvTIWtUQwKP49Uj0mkcW4rmx3k-USk
"""

!pip install biopython
import Bio

import matplotlib.pyplot as plt
import numpy as np

# -------------------------------------
#   ALINEAMIENTO DE SECUENCIAS
# -------------------------------------

from Bio import Seq

secuencia1 = Seq.Seq("ATCGATCG")
secuencia2 = Seq.Seq("ATAGATCG")

from Bio import Align
# Comenzamos creando una función de alineamiento que nos alinee las secuencias dadas
aligner = Align.PairwiseAligner(match_score=1.0)
alignments = aligner.align(secuencia1,secuencia2)

# Para visualizar los alineamientos
for alignment in alignments:
  print(alignment)

alignment = alignments[0]
sec1 , sec2 = alignment[0] , alignment[1]     # guardamos cada secuencia en un objeto

# creamos una matriz en la que las filas serán las bases de la secuencia 1
# y las columnas los elementos de la secuencia 2, cada missmatch será un 0 y
# cada match un 1:

mat = np.zeros((len(sec1),len(sec2)))
for i in range(len(sec1)):
  for j in range(len(sec2)):
    if sec1[i] == sec2[j]:
      mat[i,j] = 1

# representamos la matriz de 0 y 1 obtenida del apartado anterior

from matplotlib.colors import ListedColormap

fig = plt.figure()
ax = fig.add_subplot(111)
cmap = ListedColormap(['w', 'midnightblue'])        # creamos nuestro mapa de colores tal que 0 = blanco, 1 = azul
ax.matshow(mat, cmap = cmap)
xaxis = np.arange(len(sec1))
# añadimos las bases de las secuencias como etiquetas de los ejes
ax.set_xticks(xaxis)
ax.set_yticks(xaxis)
ax.set_xticklabels(sec2)
ax.set_yticklabels(sec1)
# y añadimos los títulos de los ejes y el gráfico
ax.set_xlabel("Secuencia 2")
ax.set_ylabel("Secuencia 1")
ax.set_title("Alineamiento de Homología")