# -*- coding: utf-8 -*-
"""FASTA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBTvTIWtUQwKP49Uj0mkcW4rmx3k-USk
"""

#Dataframe resumen a partir de archivo FASTA

import pandas as pd
import os # Import the os module for os.linesep
!pip install biopython # Install biopython
import Bio
from Bio import SeqIO

# Definimos una función que, dado un archivo FASTA, nos devuelve una tabla resumen con las características de las secuencias contenidas
# En este caso, devolverá el ID de la secuencia, su porcentaje de G-C, porcentaje de purinas y pirimidinas, y longitud de la secuencia

def resumen_fasta(Fasta_file, output_file = False):
  with open (Fasta_file, 'r') as fasta:
    lineas = [linea.rstrip(os.linesep) for linea in fasta.readlines()]
  # creamos un diccionario donde las claves son los identificadores que comienzan por '>'
  # y los valores serán las secuencias
  seqs = {}
  for linea in range(len(lineas)):
    if lineas[linea].startswith('>'):  # si la linea es un identificador guardamos su id, para ello, iteramos sobre el identificador
      n = 1                            # desde las posicion 1, para eliminar '>', hasta que encontremos un espacio.
      id = ""
      while n < len(lineas[linea]) and lineas[linea][n] != " ": # Added n < len(lineas[linea]) to prevent index out of range
        id += lineas[linea][n]
        n +=1
      for line in range(linea+1, len(lineas)):
        if lineas[line].startswith('>'):
          break
        else:
          if id in seqs:     # añadimos [1:12] para que la clave sean solo los 11 primeros valores del identificador, que se corresponden con el id
            seqs[id] = seqs[id] + lineas[line]
          else:
            seqs[id] = lineas[line]
  # creamos listas vacías para cada uno de los atributos que nos interesa
  Id_seq = []
  GC_perc = []
  Purinas_perc = []
  Pirimidinas_perc = []
  Longitud = []

  # para cada secuencia en el diccionario seqs, guardamos su id y sus características en sus respectivas listas
  for sec in seqs:
    Id_seq.append(sec)
    GC_perc.append(round((seqs[sec].count('C') + seqs[sec].count('G'))*100 / len(seqs[sec]),2))
    Purinas_perc.append(round((seqs[sec].count('A') + seqs[sec].count('G'))*100 / len(seqs[sec]),2))
    Pirimidinas_perc.append(round((seqs[sec].count('T') + seqs[sec].count('C'))*100 / len(seqs[sec]),2))
    Longitud.append(len(seqs[sec]))

# juntamos toda las diferentes listas en un diccionario que trasnformaremos a dataframe
  dic = {'Id_seq' : Id_seq, "G+C_perc" : GC_perc, "Purinas_perc" : Purinas_perc,
         "Pirimidinas_perc": Pirimidinas_perc, "Longitud": Longitud}
  dataf = pd.DataFrame(dic)

  # una vez tenemos el dataframe lo ordenamos por longitud
  dataf = dataf.sort_values(by="Longitud", ascending=False)

  # por último, si el argumento output_file es True, crearemos una fichero tsv que contenta los datos del dataframe

  if output_file == True:
    dataf.to_csv('fasta_resumen.tsv', index=False, sep='\t')

  return dataf