# -*- coding: utf-8 -*-
"""Motifs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBTvTIWtUQwKP49Uj0mkcW4rmx3k-USk
"""

!pip install biopython
import Bio

# -------------------------------------
#   Búsqueda de motivos
# -------------------------------------

def buscar_motivo(t, s):
  posiciones = []                       # creamos unas lista vacía en la que guardaremos las posiciones
  for i in range(len(t)-len(s)+1):      # por cada posición en la cadena t
    if t[i:i+len(s)] == s:              # si la subcadena desde la posición i con el largo de s es igual a s
      posiciones.append(i)              # añadimos su posicion de inicio i a la lisla posiciones
  if posiciones:                        # finalmente, si la lista no está vacía, la devoldemos
    return posiciones
  else:                                 # sino devolveremos [-1]
    return [-1]

# ----------------------------------------
# EcoRV - enzimas de restricción
# ----------------------------------------

def ecorv(seq):
  indice = seq.find("GATATC")       # la funcion find nos dará el índice donde se encuentra el motivo, o -1 en caso de que el motivo no este presente
  if indice != -1:                  # si el indice es distinto de -1, es decir, si el motivo está presente en la cadena
    cadena1 = seq[0:(indice+3)]     # la cadena 1 irá desde el inicio hasta tres posiciones mas adelante del inicio del motivo, que es el sitio de corte
    cadena2 = seq[(indice+3):]      # y la cadena 2 desde el inicio del motivo + 3 hasta el final
    cadenas = cadena1 + " + " + cadena2
  return cadenas

# ---------------------------------------
# Codones STOP
# ---------------------------------------

from Bio import SeqUtils
codons_stop = ["TAA", "TAG", "TGA"]

def encontrar_codones_stop(secuencia_adn_codificante):
  stops = {}                                                        # creamos un diccionario vacio
  for stop in codons_stop:                                          # por cada tipo de stop
    s = Bio.SeqUtils.nt_search(secuencia_adn_codificante, stop)     # lo buscaremos en la cadena y añadiremos al diccionario
    stops[stop] = s[1:]                                             # la secuencia stop como clave y sus posiciones como valor
                                                                    # como la función nt_serach nos devuelve una lista con varios elementos, el primero la
  return stops